base/urls.py
from django.urls import path
from . import views

#name for patterns
app_name = 'base'

#url patterns for base
urlpatterns = [
    path('', views.home_view, name='home')
]

omedup_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace = 'base')),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('accounts.urls', namespace = 'account')),
    path('', include('profil.urls', namespace = 'profile')),
]+ static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

profil/urls.py
from django.urls import path
from . import views
#url patterns
app_name = 'profile'
urlpatterns = [
    path('<str:slug>/', views.profile_view, name='index'),
    path('profile/<str:slug>/edit', views.profile_edit, name='edit'),
    path('profile/upload_image/<str:slug>', views.upload_avatar, name='upload_avatar'),
    path('profile/image/edit/<str:slug>', views.edit_avatar, name='edit_avatar'),
]

profil/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth.models import auth
import uuid


# Create your models here.

# pression
class Profession(models.Model):
    profession = models.CharField(max_length = 20)
    slug = models.SlugField()

    def __str__(self):
        return self.profession

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.profession)
        super(Profession, self).save(*args, **kwargs)


# profil model
class Profile(models.Model):
    CHOICES_COUNTRY = (
        ('HAITI', 'haiti'),
        ('AUTRE', 'autre')
    )
    DEPARTEMENT_CHOICES = (
        ('OUEST', 'Ouest'),
        ('GRAND\'ANSE', 'Grand\'anse'),
        ('SUD', 'Sud'),
        ('NORD', 'Nord'),
        ('NORD OUEST', 'Nord ouest'),
        ('NORD EST', 'Nord est'),
        ('SUD OUEST', 'Sud ouest'),
        ('ARTIBONITE', 'Artibonite'),
        ('CENTRE', 'Centre'),
        ('NIPPES', 'Nippes'),
    )
    STATUS_CHOICES = (
        ('ETUDIANT', 'Etudiant'),
        ('CHOMEUR', 'Chomeur'),
        ('JE TRAVAIL', 'Je travail')
    )
    ASSURANCE_CHOICES = (
        ('OUI', 'Oui'),
        ('NON', 'Non')
    )
    SEXE_CHOICES = (
        ('HOMME', 'Homme'),
        ('FEMME', 'Femme'),
        ('AUTRE', 'Autre'),
        ('CHOIX', 'Choix')
    )
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name = 'user', on_delete = models.CASCADE)
    slug = models.SlugField()
    address = models.CharField(max_length = 250, null = True)
    pays = models.CharField(max_length = 10, choices = CHOICES_COUNTRY, default = 'haiti')
    departement = models.CharField(max_length = 20, choices = DEPARTEMENT_CHOICES, default = 'Ouest')
    profession = models.ManyToManyField(Profession, related_name = 'Profession', null = True)
    status = models.CharField(max_length = 200, choices = STATUS_CHOICES, default = 'Chomage')
    assurance = models.CharField(max_length = 10, choices = ASSURANCE_CHOICES, default = 'Non')
    sexe = models.CharField(max_length = 10, choices = SEXE_CHOICES, default = 'Choix')

    def __str__(self):
        return self.user.nom

    def get_absolute_url(self):
        return reverse('profile:index', args = [self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(str(uuid.uuid4()))
        super(Profile, self).save(*args, **kwargs)

    # get avatar profil
    def get_avatar(self):
        avatar = Image.objects.get(profile = self.id)
        return avatar


# image clas for profile
class Image(models.Model):
    avatar = models.ImageField(upload_to = 'profil/avatar', null = True)
    profile = models.OneToOneField(Profile, on_delete = models.CASCADE, related_name = 'profile')
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(uuid.uuid4())
        super(Image, self).save(*args, **kwargs)

    def __str__(self):
        return self.avatar

profil/forms.py
from django import forms
from .models import Profile, Image


class ProfilForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['sexe', 'address', 'pays', 'departement', 'status', 'profession', 'assurance']
        widgets = {
            'sexe': forms.Select(attrs = { 'class': 'form-control' })
        }


class ProfileAvatarForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['avatar']

profil/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import ProfilForm, ProfileAvatarForm
from accounts.models import Account
from accounts.forms import AccountEditForm
from .models import Profile, Image
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse, HttpResponse


# Create your views here.
@login_required()
def profile_view(request, slug):
    data = get_object_or_404(Profile, slug = slug)
    context = {
        'section': 'profile',
        'profile': data
    }
    return render(request, 'profil/profil.html', context)


# edit profil
@login_required()
def profile_edit(request, slug):
    data = get_object_or_404(Profile, slug = slug)
    data1 = get_object_or_404(Account, id = request.user.id)
    if request.method == 'POST':
        form = ProfilForm(request.POST, request.FILES, instance = data)
        form_account = AccountEditForm(request.POST, instance = data1)
        if form.is_valid() and form_account.is_valid():
            form.save()
            form_account.save()
            messages.success(request, 'Modification effectue')
        else:
            messages.error(request, 'Profil non modifier a cause d\'une erreur')
    else:
        form = ProfilForm(instance = data)
        form_account = AccountEditForm(instance = data1)
    context = {
        'section': 'profil',
        'profile': data,
        'form': form,
        'form_account': form_account,
    }
    return render(request, 'profil/profil_edit.html', context)


@login_required()
def upload_avatar(request, slug):
    data = get_object_or_404(Profile, slug = slug)
    if request.method == 'POST':
        form = ProfileAvatarForm(request.POST, request.FILES)
        if form.is_valid():
            form_image = form.save(commit = False)
            form_image.profile = Profile.objects.get(id = data.id)
            form_image.save()
            messages.success(request, 'Photo Modifier')
        else:
            messages.error(request, 'Erreur inconnu, la photo n\est pas modifier')
    form = ProfileAvatarForm()
    context = {
        'form_avatar': form,
        'profile': data
    }
    return render(request, 'profil/profil_edit.html', context)

#edit profil avatar
@login_required()
def edit_avatar(request, slug):

    data = get_object_or_404(Image, slug=slug)
    if request.method == "POST":
        form = ProfileAvatarForm(request.POST, request.FILES, instance = data)
        if form.is_valid():
            form.save()
            messages.success(request, 'Photo modifié;')
            return redirect('profile:edit', slug = data.profile.slug)
        else:
            return HttpResponse('error')
    form = ProfileAvatarForm(instance = data)
    context = {
        'form_avatar': form,
        'image': data
    }
    return render(request, 'profil/profil_edit.html', context)

profil/templates/profil/profil.html
{% extends 'account/dashboard.html' %}
{% block title %}
    {{ profil.user.nom }}
{% endblock %}
{% block main %}
<div class="col-md-9">
<h3>Edit profile</h3>
    <a href="{% url 'profile:edit' profile.slug %}">modifier votre profil</a>
</div>
{% endblock %}

profil/templates/profil/profil_edit.html
{% extends 'account/dashboard.html' %}
{% load static %}
{% block title %}
    {{ profil.user.nom }}
{% endblock %}
{% block main %}
    <div class="col-md-10">
        <div class="row">
             <div class="col-md-8">
                 <h3 class="text-center">Modifier mes information</h3>
                 {% if messages %}
                    {% for message in messages %}
                        <div class="text-{{ message.tags }}">
                        {{ message }}
                        </div>
                    {% endfor %}

                 {% endif %}
                 <hr>
                 <div class="form-section border">
                     <form method="POST" enctype="multipart/form-data">
                         {% csrf_token %}
                         <div class="form-section-row">
                             <div class="form-input">
                                 <label for="{{ form_account.nom.id_for_label }}">{{ form_account.nom.label }}</label>
                                {{ form_account.nom }}
                             </div>
                             <div class="form-input">
                                 <label for="{{ form_account.prenom.id_for_label }}">{{ form_account.prenom.label }}</label>
                                {{ form_account.prenom }}
                             </div>
                         </div>
                         <div class="form-section-row">
                             <div class="form-input">
                                 <label for="{{ form_account.age.id_for_label }}">{{ form_account.age.label }}</label>
                                {{ form_account.age }}
                             </div>
                             <div class="form-input">
                                 <label for="{{ form.sexe.id_for_label }}">{{ form.sexe.label }}</label>
                                {{ form.sexe }}
                             </div>
                         </div>
                         <div class="form-section-row">
                             <div class="form-input">
                                 <label for="{{ form.address.id_for_label }}">{{ form.address.label }}</label>
                                {{ form.address }}
                             </div>
                             <div class="form-input">
                                 <label for="{{ form.pays.id_for_label }}">{{ form.pays.label }}</label>
                                {{ form.pays }}
                             </div>
                         </div>
                         <div class="form-section-row">
                             <div class="form-input">
                                 <label for="{{ form.departement.id_for_label }}">{{ form.departement.label }}: </label>
                                {{ form.departement }}
                             </div>
                             <div class="form-input">
                                 <label for="{{ form.status.id_for_label }}">{{ form.status.label }}: </label>
                                {{ form.status }}
                             </div>
                         </div>
                         <div class="form-section-row">
                             <div class="form-input">
                                 <label for="{{ form.profession.id_for_label }}">{{ form.profession.label }}: </label>
                                {{ form.profession }}
                             </div>
                             <div class="form-input">
                                 <label for="{{ form.assurance.id_for_label }}">{{ form.assurance.label }}: </label>
                                {{ form.assurance }}
                             </div>
                         </div>
                         <div class="button">
                              <button type="submit" class="btn service-button">Enregistrer</button>
                         </div>
                     </form>
                 </div>
             </div>
        <div class="col-md-4 p-4 border-start">
            <h3 class="text-center">Mes informations</h3>
        {% if profile.profile.avatar %}
            <form action="{% url 'profile:edit_avatar' profile.profile.slug %}" method="POST" enctype="multipart/form-data" class="form-avatar" id="image-form">
            {% csrf_token %}
            <div class="avatar-profil">
                 <img src="{{ profile.profile.avatar.url }}" alt="avatar" class="image-size" id="output">
            </div>
            <div class="avatar-input">
                <input type="file" name="avatar" accept="image/*" onchange="showPreview(event);">
            </div>
            <input type="submit" value="Enregistrer" id="enregistrer">
            </form>
            {% else %}
             <form action="{% url 'profile:upload_avatar' profile.slug %}" method="POST" enctype="multipart/form-data" class="form-avatar" id="image-form">
            {% csrf_token %}
            <img src="{% static 'avatar/avatar.png' %}" alt="avatar" class="image-size">
            <div class="avatar-input">
                <input type="file" accept="image/*" name="avatar" id="avatar">
            </div>
            <input type="submit" value="Enregistrer" id="enregistrer">
            </form>
         {% endif %}
            <hr>
             {% if profile %}
                <p><b>Nom:</b> {{ profile.user.nom }} {{ profile.user.prenom }}</p>
                 <p><b>Date de naissance:</b> {{ profile.user.age }}</p>
                 <p><b>Sexe:</b> {{ profile.sexe }}</p>
                 <p><b>Adresse:</b> {{ profile.address }}, {{ profile.departement }}, {{ profile.pays }}</p>
                 <p><b>Status:</b> {{ profile.status }} </p>
                 <p><b>Profession:</b> {{ profile.profession }} </p>
                 <p><b>Carte d'assurance:</b> {{ profile.assurance }} </p>
                 <a href="#">Modifier mes informations</a>
                 <p><a href="#">Retourner a mon profile</a></p>

            {% endif %}
        </div>
        </div>
    </div>
    <script>
    function showPreview(event){
  if(event.target.files.length > 0){
    let src = URL.createObjectURL(event.target.files[0]);
    console.log(src)
    let preview = document.getElementById("output");
    preview.src = src;
    preview.style.display = "block";
  }
}
    </script>
{% endblock %}