accounts/urls.py
from django.urls import path
from . import views
#url patter
app_name = 'account'
urlpatterns = [
    path('registration', views.registration_view, name="registration"),
    path('dashboard', views.dashboard, name='dashboard')
]

base/urls.py
from django.urls import path
from . import views

#name for patterns
app_name = 'base'

#url patterns for base
urlpatterns = [
    path('', views.home_view, name='home')
]

omedup_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace = 'base')),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('accounts.urls', namespace = 'account')),
    path('', include('profil.urls', namespace = 'profile')),
]+ static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

templates/components/banner.html
<div class="banner">
    <div class="banner-item">
        <h3>Retrouver les services medicales de votre choix</h3>
        <button class="btn button-item">Service</button>
    </div>
</div>

templates/components/footer.html
<div class="container">
    <h3>footer</h3>
</div>

templates/components/navigation.html
{% load static %}
{% load active_link_tags %}
<header class="navigation">
    <div class="brand">
        <img src="{% static 'logo/logo_omedup.png' %}" alt="logo" class="logo">
    </div>
        <div class="menu-toogle inactive-menu" id="menu-toogle"></div>
        <div class="navbar-all inactive">
            <ul class="navbar-list">
            {% url 'base:home' as home %}
            <li><a href="{% url 'base:home' %}" class="{% if request.path == home %}active{% endif %}"><i class="fas fa-home"></i> Home</a></li>
            <li><a href="#" ><i class="fas fa-info-circle"></i> About</a></li>
            <li><a href="#"><i class="fas fa-address-book"></i> Contact</a></li>
        </ul>
             <div class="form-search">
                <form action="#">
                    <input type="search" name="search" id="search" placeholder="Search">
                </form>
                 <span><i class="fas fa-search"></i></span>
            </div>
            {% if user.is_authenticated %}
                <ul class="account">
                {% if section and section == 'dashboard' %}
                    <li><a href="{{ account.get_profile.get_absolute_url }}">Profile</a></li>
                    {% else %}
                <li><a href="{% url 'account:dashboard' %}" class="{% active_link 'account:dashboard' 'active' %}">Dashboard</a></li>
                {% endif %}
                 <li><a href="{% url 'logout' %}">Log out</a></li>
                <li class="avatar-profil">
                 <a href="#">
                    {% if request.user.get_profile.profile.avatar  %}
                        <img src="{{ request.user.get_profile.profile.avatar.url }}" alt="profil">
                    {% else %}
                        <i class="fas fa-user-circle"></i>
                         {% endif %}
                        </a>
                        </li>
                </ul>
            {% else %}
                <ul class="account">
                    <li><a href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i>Login</a></li>
                    <li><a href="{% url 'account:registration' %}"><i class="fas fa-user-plus"></i> register</a></li>
                </ul>
            {% endif %}
        </div>
</header>

templates/components/navigation_left.html
<div class="navbar-left sticky">
    <ul>
        <li>
            <a href="{{ profile.get_absolute_url }}" class="{% if request.path == profile.get_absolute_url %}
                        active{% endif %}"><i class="fas fa-user"></i> Profil</a>
        </li>
        <li><a href="#"><i class="fas fa-notes-medical"></i> Prescription</a></li>
        <li><a href="#"><i class="fas fa-user-md"></i> Medecins</a></li>
        <li><a href="#"><i class="fas fa-comment-medical"></i> Recommendations</a></li>
        <li><a href="#"><i class="fas fa-prescription"></i> Pharmacie</a></li>
        <li><a href="#"><i class="fas fa-pump-medical"></i> Laboratoires</a></li>
        <li><a href="#"><i class="fas fa-hospital"></i> Hopital</a></li>
    </ul>
</div>